Fix create images to work with Docker
Maistra/istio-images-centos pull request #55
Opened 2021-01-05 22:22 UTC by brian-avery

Create-images.sh `push` doesn't currently work with Docker. This is because podman and docker list images differently. While podman always lists the hub, docker swallows it if it's pointing at dockerhub. This PR fixes the script to use a hub of "maistra" by default if docker is used and otherwise "docker.io/maistra"

2021-01-06 09:42 UTC, dgn commented on create-images.sh
> +    HUB="maistra"
is this really necessary?

2021-01-06 14:31 UTC, brian-avery commented on create-images.sh
> +    HUB="maistra"
The real problem here is https://github.com/brian-avery/istio-images-centos/blob/FixCreateImagesToWorkWithDocker/create-images.sh#L131. We tag the images based on the HUB, docker sees "maistra" and "docker.io/maistra" as equivalent and displays it as "maistra" in docker images, and the grep fails because nothing exists as "docker.io/maistra"

2021-01-06 14:37 UTC, brian-avery commented on create-images.sh
> +    HUB="maistra"
None of the arguments to `docker images` seem to display the hub as well.

2021-01-15 12:57 UTC, dgn approved these changes

2021-01-15 14:16 UTC, jwendell requested changes
Basically you need an `else` in `verify_podman()`

2021-01-15 14:16 UTC, jwendell commented on create-images.sh
> +  if ! cli_is_podman; then
This assignment could be done inside `verify_podman()`, in an `else` statement there. Thus this function can be dropped.

2021-01-15 14:16 UTC, jwendell commented on create-images.sh
> +function verify_podman {
don't remove `()`

2021-01-15 14:16 UTC, jwendell commented on create-images.sh
> +set_proper_hub
This could be removed as per comment above.

2021-01-15 14:16 UTC, jwendell commented on create-images.sh
> +function cli_is_podman() {
This function can be removed and the `if` statement in `verify_podman()` could be back to the original one.

2021-01-15 15:39 UTC, brian-avery commented on create-images.sh
> +function verify_podman {
Good catch. Interesting. I wonder why this worked in both GitHub and locally as well as passed Shellshock. I would have guessed that at least one of them would have caught it. Let me fix it. Thanks.

2021-01-15 15:43 UTC, brian-avery commented on create-images.sh
> +  if ! cli_is_podman; then
The problem with doing it in an else statement in verify_podman is that it prevents users from overriding the HUB

2021-01-15 15:44 UTC, brian-avery commented on create-images.sh
> +function cli_is_podman() {
It can be, but this is used in multiple places and I think the function makes the code cleaner.

2021-01-15 15:46 UTC, jwendell commented on create-images.sh
> +  if ! cli_is_podman; then
You could move it, or rather check the value of HUB before blindly assigning it to a value. Also, that would require refactor the check for root user in `verify_podman`.

2021-01-15 15:47 UTC, jwendell commented on create-images.sh
> +function cli_is_podman() {
It won't be used in multiple places if you follow my other comments

2021-01-15 15:50 UTC, brian-avery commented on create-images.sh
> +  if ! cli_is_podman; then
How would you propose checking if the user wants, say: 

docker.io/quay.io/foo
docker.io/maistra/foo
quay.io/foo

It seemed to me, the simplest way to do this was to fix the URL to begin with and allow the user to override it to whatever they need to be. I originally had a solution like you were proposing above, but thought there was greater value in setting a correct value to begin with and allowing the user to override if they wanted something different rather than overriding what the user put in.

2021-01-15 15:51 UTC, brian-avery commented on create-images.sh
> +  if ! cli_is_podman; then
Not sure what refactor you are saying this needs. What's here already works.

2021-01-15 16:43 UTC, jwendell commented on create-images.sh
> +  if ! cli_is_podman; then
Yeah, I made those suggestions to keep the changes minimal. About rewriting the HUB, what I had in mind was: `if HUB == docker.io/maistra AND cli is not podman then HUB=maistra`. This rewriting would happen after we set the HUB variable by the user. Does it make sense?

2021-01-15 16:54 UTC, jwendell commented on create-images.sh
> +  if ! cli_is_podman; then
or, more generic, `if hub starts with docker.io and cli is not podman then remove docker.io/ from HUB`

2021-11-22 15:21 UTC, jwendell commented
Closing this one as obsolete.

2021-11-22 15:21 UTC, closed without merging